on:
    push:
jobs:
    # Build job
    build:
      if: github.actor == 'stuyk'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
            - name: Setup NodeJS
              uses: actions/setup-node@v3
            - name: Install and Build ðŸ”§
              run: |
                  npm install
                  npm run docs
            - name: Deploy ðŸš€
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
            - name: Invoke Documentation Build
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: deploy.yml
                  repo: stuyk/athena-docs-latest
                  token: ${{ secrets.DOCS_PAT }}
